android_ip_webcam: !include android_webcams.yaml

alarm_control_panel: !include alarm.yaml

automation: !include_dir_merge_list automations

binary_sensor: !include binary_sensors.yaml

camera: !include cameras.yaml

default_config:

device_tracker: !include device_trackers.yaml

discovery:

fastdotcom:
  scan_interval:
    minutes: 30
    
group: !include groups.yaml

homeassistant:
  name: Potsdam
  latitude: 52.4150
  longitude: 13.0466
  elevation: 54
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/snapshots
    - /config/www

ifttt:
  key: !secret ifttt_key

input_select: !include input_select.yaml

light: !include lights.yaml

logger:
  default: info

media_player: !include mediaplayers.yaml

mqtt: !include mqtt.yaml

notify: !include notify.yaml

panel_iframe: !include iframes.yaml

person: !include person.yaml

recorder:
  purge_keep_days: 100
  purge_interval: 1

shell_command: !include shell_commands.yaml

script: !include_dir_merge_named scripts/

sensor: !include sensors.yaml

stream:

telegram_bot: !include telegram_bot.yaml

tts:
  - platform: google_translate

vacuum:
  - platform: xiaomi_miio
    host: 192.168.177.46
    token: !secret xiaomi_miio_vacuum_token

wake_on_lan:

webostv: !include webostv.yaml

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 7811DCF78FD3
      key: !secret xiaomi_gw_key

zone: !include zones.yaml