- platform: mqtt
  schema: json
  name: kitchen_white_left
  command_topic: "home-assistant/sensors/ms-kha-kl/led/white/command"
  state_topic: "home-assistant/sensors/ms-kha-kl/led/white/state"
  brightness: true
  brightness_scale: 1000

- platform: mqtt
  schema: json
  name: kitchen_blue_left
  command_topic: "home-assistant/sensors/ms-kha-kl/led/blue/command"
  state_topic: "home-assistant/sensors/ms-kha-kl/led/blue/state"
  brightness: true
  brightness_scale: 1000

- platform: mqtt
  schema: json
  name: kitchen_white_right
  command_topic: "home-assistant/sensors/ms-kha-kr/led/white/command"
  state_topic: "home-assistant/sensors/ms-kha-kr/led/white/state"
  brightness: true
  brightness_scale: 1000

- platform: mqtt
  schema: json
  name: kitchen_blue_right
  command_topic: "home-assistant/sensors/ms-kha-kr/led/blue/command"
  state_topic: "home-assistant/sensors/ms-kha-kr/led/blue/state"
  brightness: true
  brightness_scale: 1000
  
- platform: hyperion
  host: 192.168.177.93
  
#- platform: mqtt
#  schema: json
#  name: christmastree
#  command_topic: "home-assistant/sensors/ms-kha-kr/led/blue/command"
#  state_topic: "home-assistant/sensors/ms-kha-kr/led/blue/state"
#  brightness: true
#  brightness_scale: 255