- alias: Fernseher an
  trigger:
    - platform: event
      event_type: tv_on
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay: '00:00:03'
    - service: media_player.turn_on
      entity_id: media_player.living_room_tv

- alias: TV Rack aus
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  action:
    - service: switch.turn_off
      entity_id: switch.tv
      
- alias: 'Katzenbrunnen motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001a8d3ed
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: 'switch.sonoff_2'
            state: 'off'
          - condition: time
            after: '07:00:00'
          - condition: time
            before: '12:00:00'
      - condition: and
        conditions:
          - condition: state
            entity_id: 'switch.sonoff_2'
            state: 'off'
          - condition: time
            after: '15:00:00'
          - condition: time
            before: '22:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_2
    - delay: '00:01:00'
    - service: switch.turn_off
      entity_id: switch.sonoff_2
      
- alias: 'Suspend katzenbrunnen automation'
  trigger:
    - platform: state
      entity_id: switch.sonoff_2
      to: 'off'
  action:
    - service: automation.turn_off
      entity_id: automation.katzenbrunnen_motion
    - delay: '00:15:00'
    - service: automation.turn_on
      entity_id: automation.katzenbrunnen_motion

- alias: 'Katzenbrunnen cron'
  trigger:
    - platform: time_pattern
      minutes: 01
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: 'switch.sonoff_2'
            state: 'off'
          - condition: time
            after: '07:00:00'
          - condition: time
            before: '12:00:00'
      - condition: and
        conditions:
          - condition: state
            entity_id: 'switch.sonoff_2'
            state: 'off'
          - condition: time
            after: '15:00:00'
          - condition: time
            before: '22:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_2
    - delay: '00:05:00'
    - service: switch.turn_off
      entity_id: switch.sonoff_2
      
- alias: 'Mikrowelle an'
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '13:00:00'
    - platform: time
      at: '16:00:00'
    - platform: time
      at: '19:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_3

- alias: 'Mikrowelle aus'
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_3